[project]
site_name = "Fractal Tasks Core"
site_url = "https://fractal-analytics-platform.github.io/fractal-tasks-core/"
repo_url = "https://github.com/fractal-analytics-platform/fractal-tasks-core"
repo_name = "fractal-analytics-platform/fractal-tasks-core"
extra_css = ["extra.css"]
copyright = """
Copyright 2026 (C) BioVisionCenter (University of Zurich) - see
<u><a href="https://github.com/fractal-analytics-platform/fractal-tasks-core/blob/main/LICENSE">LICENSE</a></u>.
"""

nav = [
    { "Home" = "index.md" },
    { "Install" =  "install.md" },
    { "Development" = "development.md" },
    { "Changelog" = "changelog.md" },
    { "Code reference" = "code_reference/" },
]

[project.theme]
variant = "classic"
language = "en"
logo = "https://raw.githubusercontent.com/fractal-analytics-platform/fractal-logos/refs/heads/main/common/fractal_logo.png"
favicon = "https://raw.githubusercontent.com/fractal-analytics-platform/fractal-logos/refs/heads/main/common/fractal_favicon.png"
custom_dir = "docs/overrides"
navigation = {"expand" = true}

features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.path",
    "navigation.sections",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "search.highlight",
    "toc.follow",
    "toc.integrate",
]


[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "deep purple"
accent = "light blue"
toggle.icon = "material/weather-night"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "deep purple"
accent = "light blue"
toggle.icon = "material/weather-sunny"
toggle.name = "Switch to light mode"

[project.plugins.search]

[project.plugins.autorefs]
resolve_closest=true

[project.plugins.section-index]


[project.plugins.mkdocstrings.handlers.python]
paths = ["fractal_tasks_core"]
inventories = [
    "https://docs.python.org/objects.inv",
    "https://numpy.org/doc/stable/objects.inv",
    "https://zarr.readthedocs.io/en/stable/objects.inv",
    "https://anndata.readthedocs.io/en/latest/objects.inv",
    "https://docs.dask.org/en/stable/objects.inv",
    "https://docs.pydantic.dev/latest/objects.inv",
]

[project.plugins.mkdocstrings.handlers.python.options]

paths = ["fractal_tasks_core"]
filters = []

group_by_category = true
show_category_heading = true
summary = true

backlinks = "tree"
docstring_style = "google"
docstring_section_style = "spacy"
show_source = true

parameter_headings = true
allow_inspection = true
show_symbol_type_heading = true
show_symbol_type_toc = false
signature_crossrefs = true
unwrap_annotated = true
show_attribute_values = true
inherited_members = true
extensions= ["griffe_pydantic"]
