name: CI (pixi)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "v2"]

jobs:

  tests_core:
    name: "Core, Python ${{ matrix.python-version }}"
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false

      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          environments: dev
          pixi-version: "latest"

      - name: Test core library with pytest
        env:
          COVERAGE_FILE: coverage-data-core-${{ matrix.python-version }}
        run: pixi run --environment dev coverage run -m pytest tests --ignore tests/tasks --ignore tests/tasks_v2

      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data-core-${{ matrix.python-version }}
          path: coverage-data-core-${{ matrix.python-version }}*

  tests_tasks:
    name: "Tasks, Python ${{ matrix.python-version }}"
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false

      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          environments: dev
          pixi-version: "latest"

      - name: Check if manifest has changed
        run: pixi run --environment dev fractal-manifest check --package fractal-tasks-core

      - name: Cache Pooch folder
        id: cache-pooch-folder
        uses: actions/cache@v4
        with:
          path: ~/.cache/pooch
          key: pooch-cache

      - name: Test tasks with pytest
        env:
          COVERAGE_FILE: coverage-data-tasks-${{ matrix.python-version }}
        run: pixi run --environment dev coverage run -m pytest tests/tasks tests/tasks_v2

      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data-tasks-${{ matrix.python-version }}
          path: coverage-data-tasks-${{ matrix.python-version }}*

  coverage:
    name: Coverage
    runs-on: ubuntu-24.04
    needs: [tests_core, tests_tasks]
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          environments: dev
          pixi-version: "latest"

      - name: Download data
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-data-*
          merge-multiple: true

      - name: Combine coverage
        run: pixi run --environment dev coverage combine coverage-data-*

      - name: Add coverage comment to Pull Requests
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          MINIMUM_GREEN: 90
          MINIMUM_ORANGE: 60
          ANNOTATE_MISSING_LINES: true
          ANNOTATION_TYPE: notice
