name: docs

on:
  push:
    branches: ["main","dev-1.5"]
  pull_request:
    branches: ["main","dev-1.5"]

jobs:

  docs:
    name: "Deploy docs"
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: docs/doc-requirements.txt

  docs-build:
    name: "Test docs build"
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'push' || github.ref != 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Install dependencies
        run: python -m pip install -r docs/doc-requirements.txt

      - name: MKDocs build
        run: mkdocs build --config-file mkdocs.yml --strict
