name: Precommit, Ruff and Mypy (soft)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  package:
    name: "Precommit, Ruff and Mypy (soft)"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: pip

      - name: Run pre-commit (fail upon errors)
        uses: pre-commit/action@v3.0.1

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff check (do not fail for errors)
        continue-on-error: true
        run: ruff check fractal_tasks_core

      - name: Install ty
        run: pip install ty

      - name: Run ty (do not fail for errors)
        continue-on-error: true
        run: ty check fractal_tasks_core
