name: Precommit, Ruff and Mypy (soft)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: {}

jobs:

  package:
    name: "Precommit, Ruff and Mypy (soft)"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python 3.11
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.11"
          cache: pip

      - name: Run pre-commit (fail upon errors)
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff check (do not fail for errors)
        continue-on-error: true
        run: ruff check fractal_tasks_core

      - name: Install ty
        run: pip install ty

      - name: Run ty (do not fail for errors)
        continue-on-error: true
        run: ty check fractal_tasks_core
