name: Build package

on:
  push:
    branches: ["main", "dev-1.5"]
  pull_request:
    branches: ["main", "dev-1.5"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: "Set up Python 3.11"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: "Install poetry 1.8.2"
        run: curl -sSL https://install.python-poetry.org | python3 - --version 1.8.2

      - name: Build package
        run: poetry build
