name: Build package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: "Set up Python 3.11"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: "Install poetry 1.8.5"
        run: curl -sSL https://install.python-poetry.org | python3 - --version 1.8.5

      - name: Build package
        run: poetry build
